### ISSUE TITLE
test 

### ISSUE THREAD

**Issue by cata332** [MikaelaNeia/recovery_device_xiaomi_agate#1]
pls let me test your build

**Comment by MikaelaNeia** [comment]
> pls let me test your build

https://github.com/MikaelaNeia/Action-Recovery-Builder/releases/download/3086484452/boot.img

installation:
1. backup you stock rom boot.img
2. flash twrp
3. reboot to twrp
4. flash stock rom boot.img
5. click advanced>flash current twrp
6. reboot system
8. and try reboot to twrp again
